grafana/grafana-polystat-panel

dist/partials/editor.composites.html, src/partials/editor.composites.html
refactoring introduced bug when deleting a composite (calling wrong method)
=> fix remove composite bug

.gitignore, src/ctrl.ts, src/styles/polystat.scss
=> Fix for issue #61 Singlestat panel value is shown over Polystat tooltip

src/ctrl.ts
=> Add square option 

README.md
it fixes the broken grafana.org link
=> fixed the broken grafana link in readme

.circleci/config.yml
=> Build: update circle build

.theia/settings.json, src/composites_manager.ts, src/metric_overrides_manager.ts, src/partials/editor.composites.html
Why?
1. To allow templates to be used in autocreating composites
2. To allow multiple composites to be created from a single template
3. To allow matching overrides against a template.
=> metric and override enhancements

CHANGELOG.md, src/metric_overrides_manager.ts
=> Override evaluation fix

.circleci/config.yml
set plugin name after jq is installed and dist is copied into place
=> fix publish step in circleci

.gitignore, .prettierrc.js, README.md, package.json, yarn.lock
lets update to latest toolkit for better CI integration
=> use toolkit@next

src/d3wrapper.ts
Added functionality to display the name with ellipsis on the polygon when the name contains too many characters.
=> Updated d3wrapper.ts file

src/ctrl.ts, src/partials/editor.mappings.html
Added value mappings for global section
=> Add global value mapping

src/styles/polystat.scss
Changed the polystat tool-tip width to min-content as the text is going outside the tool-tip container.
=> Updated polystat.scss file

src/ctrl.ts, src/d3wrapper.ts, src/partials/editor.options.html
Hi,
i've added an option to set a custom font-color value. This should resolve one item of #49 too.
=> Add option to add/ change inline hexagon font color

src/ctrl.ts
At present there is no provision for show or hide the value on polygon so we added that feature.
=> Updated Ctrl.ts file

src/types.ts
At present there is no provision for show or hide the value on polygon so we added that feature.
=> Updated types.ts

src/partials/editor.options.html
At present there is no provision for show or hide the value on polygon so we added that feature.
=> Updated editor.options.html

src/tooltip.ts
At present there is no provision for show or hide the value on polygon so we added that feature.
=> Updated tooltip.ts

.circleci/config.yml, .codeclimate.yml, .drone.yml, CHANGELOG.md, package.json, src/ctrl.ts, src/d3wrapper.ts, src/layoutManager.test.ts, src/layoutManager.ts, src/metric_overrides_manager.ts, src/partials/editor.options.html, src/plugin.json, src/styles/polystat.scss, yarn.lock
=> bugfixes and release prep

CHANGELOG.md, package.json, src/color.test.ts, src/color.ts, yarn.lock
=> fix for issue 126 gradients

src/d3wrapper.ts
=> Fix circles and rectangles creation when clickThroughURL is filled

src/styles/polystat.scss
=> Increase polystat-panel-tooltip z-index

CHANGELOG.md, package.json, src/d3wrapper.ts, yarn.lock
code was referencing data and not the computed coordinates
=> fix offsets for circle/square shapes

src/d3wrapper.ts
=> Compute X and Y mouse positions in mouseover

package.json, src/metric_overrides_manager.test.ts, src/metric_overrides_manager.ts, yarn.lock
=> Support global value mappings in Overrides

src/ctrl.ts, src/d3wrapper.ts, src/partials/editor.options.html, src/types.ts
Add the "Enable tooltips" switch controller :
=> Add a switch controller to show/hide tooltips

src/ctrl.ts, src/metric_overrides_manager.ts
=> Fix '0' value mapping not working

src/ctrl.ts, src/metric_overrides_manager.ts, src/partials/editor.options.html, src/partials/editor.overrides.html
=> RegexSupport

.circleci/config.yml, CHANGELOG.md, package.json, src/ctrl.ts, src/layoutManager.ts, src/metric_overrides_manager.test.ts, src/utils.test.ts, src/utils.ts, yarn.lock
=> [WIP] bugfixes

.config/README.md, .config/jest.config.js, .config/mocks/react-inlinesvg.tsx, .config/tsconfig.json, .config/webpack/webpack.config.ts, CHANGELOG.md, package.json, src/data/processor.ts, yarn.lock
Fixes #240
This is a quick fix for applying the global regex, which was not updating the display name.
=> minor update to fix global regex and transforms

.config/README.md, .config/jest.config.js, .config/mocks/react-inlinesvg.tsx, .config/tsconfig.json, .config/webpack/webpack.config.ts, CHANGELOG.md, package.json, src/data/processor.ts, yarn.lock
merge from v2.x
* fix for bug #240
* update create-plugin
=> minor update to fix global regex and transforms (#243)

.github/workflows/stale.yml
Introducing stalebot to keep issues and PRs up to date
=> Adding stalebot

src/components/Polystat.tsx, src/components/PolystatPanel.tsx, src/components/tooltips/Tooltip.test.tsx, src/components/tooltips/Tooltip.tsx, src/components/types.ts, src/migrations.ts, src/module.ts
=> remove column headers feature

.github/dependabot.yml
Adding dependabot config to auto-create PRs for dependency updates
=> Adding dependbot config

src/components/Polystat.tsx, src/components/PolystatPanel.tsx, src/components/defaults.ts, src/components/styles.ts
=> refactor and implement display limit warning message

CHANGELOG.md, docker-compose.yml, package.json
=> bump version and update changelog

CHANGELOG.md
- prep release
- version is already set to 2.1.3
- changelog updated
=> prep for 2.1.3 release

CHANGELOG.md, package.json, src/components/Polystat.tsx, src/data/deframer.ts, src/data/processor.ts, tests/auth-bypassed/phase2-installed/check-installed.spec.ts
- Fixes compatibility issue between older versions of Grafana
- Fixes tooltip issue when toggling enable/disable in editor mode
- Updates playwright test to detect version from package.json
Fixes: #389 
Fixes: #387 
Fixes: #388 ( thanks @academo )
=> workaround for api removal at runtime
